package com.wordpress.salaboy.examples;

import com.wordpress.salaboy.example.model.Ambulance;
import com.wordpress.salaboy.example.model.Vehicle;
import com.wordpress.salaboy.example.model.FireTruck;
import com.wordpress.salaboy.example.model.Emergency;
import com.wordpress.salaboy.example.persistence.PersistentProcessManager;

rule "New Ambulance for Heart Attack Emergencies"
    ruleflow-group "select_vehicle"
    when
        $processManager: PersistentProcessManager()
        Emergency(type == "Heart Attack") from $processManager.getProcessVariable("emergency")

    then
        System.out.println("A new Ambuance is being created!");
        Ambulance ambulance = new Ambulance("MyAmbulance");
        $processManager.setProcessVariable("vehicle", ambulance);
        insert(ambulance);
end

rule "New Fire Truck for Fire Emergencies"
    ruleflow-group "select_vehicle"
    when
        $processManager: PersistentProcessManager()
        Emergency(type == "Fire") from $processManager.getProcessVariable("emergency")

    then
        System.out.println("A new FireTruck is being created!");
        FireTruck fireTruck = new FireTruck("MyFireTruck");
        $processManager.setProcessVariable("vehicle", fireTruck);
        insert(fireTruck);
end