package com.wordpress.salaboy.rete;

import com.wordpress.salaboy.model.*;


rule "Match all the persons with name Salaboy and older than 18 years old"
    when
    	
    	$address: Address(addressLine1 == "nowhere")
        $person: Person( name == "Salaboy", age > 18, address == $address)
    then
        System.out.println("Hey I just find "+$person);
end

rule "Same rule as before but the field restrictions are backwards"
    when
    	
    	$address: Address(addressLine1 == "nowhere")
        $person: Person(name == "Salaboy", age > 18, address == $address)
        
    then
        System.out.println("2 - Hey I just find "+$person);
end